#!/bin/bash

# BLV Security Kiosk - Interactive Setup Script
# This script configures a new Raspberry Pi kiosk installation

set -e

echo "========================================="
echo "BLV Security Kiosk - Setup"
echo "========================================="
echo ""
echo "This script will configure your Raspberry Pi kiosk."
echo "You'll need the following information:"
echo "  - Unifi Protect server IP address"
echo ""

# Get Unifi Protect IP
while true; do
    read -p "Enter Unifi Protect IP address (e.g., 192.168.3.1): " UNIFI_IP

    # Basic IP validation
    if [[ $UNIFI_IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        echo "Testing connection to $UNIFI_IP..."
        if ping -c 1 -W 2 "$UNIFI_IP" > /dev/null 2>&1; then
            echo "✓ Connection successful!"
            break
        else
            echo "⚠ Warning: Cannot ping $UNIFI_IP"
            read -p "Continue anyway? (y/n): " continue_anyway
            if [[ $continue_anyway == "y" || $continue_anyway == "Y" ]]; then
                break
            fi
        fi
    else
        echo "Invalid IP address format. Please try again."
    fi
done

# Generate URL
UNIFI_URL="https://${UNIFI_IP}/protect/dashboard/all"

# Confirm settings
echo ""
echo "========================================="
echo "Configuration Summary"
echo "========================================="
echo "Unifi Protect IP: $UNIFI_IP"
echo "Unifi Protect URL: $UNIFI_URL"
echo ""
read -p "Is this correct? (y/n): " confirm

if [[ $confirm != "y" && $confirm != "Y" ]]; then
    echo "Setup cancelled."
    exit 1
fi

# Create config file
echo ""
echo "Creating configuration file..."
CONFIG_FILE="$HOME/kiosk-config.sh"

cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# BLV Security Kiosk Configuration
# This file is generated by setup.sh and should not be committed to git
# Generated on: $(date)

# Unifi Protect Configuration
export UNIFI_PROTECT_IP="$UNIFI_IP"
export UNIFI_PROTECT_URL="$UNIFI_URL"

# Chromium Configuration Flags
export CHROMIUM_FLAGS="--kiosk --start-fullscreen --password-store=basic --noerrdialogs --disable-infobar --disable-features=TranslateUI --disable-sync --disable-default-apps --no-first-run --disable-session-crashed-bubble --hide-crash-restore-bubble --disk-cache-size=104857600 --media-cache-size=104857600 --disable-background-timer-throttling --js-flags=--max-old-space-size=2048"

# Display Configuration
export WAYLAND_DISPLAY=wayland-0
export DISPLAY=:0
EOF

chmod 600 "$CONFIG_FILE"
echo "✓ Configuration saved to $CONFIG_FILE"

# Install scripts
echo ""
echo "Installing scripts..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ -d "$SCRIPT_DIR/scripts" ]; then
    cp "$SCRIPT_DIR/scripts/"*.sh "$HOME/"
    chmod +x "$HOME/"*.sh
    echo "✓ Scripts copied to home directory"
else
    echo "⚠ Warning: scripts directory not found"
fi

# Install autostart configs
echo ""
read -p "Install autostart configurations? (y/n): " install_autostart

if [[ $install_autostart == "y" || $install_autostart == "Y" ]]; then
    mkdir -p "$HOME/.config/autostart"

    if [ -d "$SCRIPT_DIR/autostart-configs" ]; then
        cp "$SCRIPT_DIR/autostart-configs/unifi-protect.desktop" "$HOME/.config/autostart/"
        cp "$SCRIPT_DIR/autostart-configs/screen-timeout.desktop" "$HOME/.config/autostart/"
        cp "$SCRIPT_DIR/autostart-configs/network-monitor.desktop" "$HOME/.config/autostart/"
        echo "✓ Autostart configurations installed"
        echo "  Note: chromium-refresh.desktop.disabled is not installed (disabled by default)"
    else
        echo "⚠ Warning: autostart-configs directory not found"
    fi
fi

# Install desktop shortcuts
echo ""
read -p "Install desktop shortcuts? (y/n): " install_shortcuts

if [[ $install_shortcuts == "y" || $install_shortcuts == "Y" ]]; then
    mkdir -p "$HOME/Desktop"

    if [ -d "$SCRIPT_DIR/desktop-shortcuts" ]; then
        cp "$SCRIPT_DIR/desktop-shortcuts/"* "$HOME/Desktop/"
        chmod +x "$HOME/Desktop/"*.sh
        echo "✓ Desktop shortcuts installed"
    else
        echo "⚠ Warning: desktop-shortcuts directory not found"
    fi
fi

# Install daily reboot cron job
echo ""
read -p "Install daily 3 AM reboot cron job? (requires sudo) (y/n): " install_cron

if [[ $install_cron == "y" || $install_cron == "Y" ]]; then
    echo "0 3 * * * root /usr/sbin/reboot" | sudo tee /etc/cron.d/daily-reboot > /dev/null
    sudo chmod 644 /etc/cron.d/daily-reboot
    echo "✓ Daily reboot cron job installed"
fi

# Check dependencies
echo ""
echo "Checking dependencies..."
MISSING_DEPS=()

command -v chromium > /dev/null || MISSING_DEPS+=("chromium")
command -v swayidle > /dev/null || MISSING_DEPS+=("swayidle")
command -v wlopm > /dev/null || MISSING_DEPS+=("wlopm")
command -v xdotool > /dev/null || MISSING_DEPS+=("xdotool")

if [ ${#MISSING_DEPS[@]} -gt 0 ]; then
    echo "⚠ Missing dependencies: ${MISSING_DEPS[*]}"
    read -p "Install missing dependencies? (requires sudo) (y/n): " install_deps

    if [[ $install_deps == "y" || $install_deps == "Y" ]]; then
        sudo apt-get update
        sudo apt-get install -y "${MISSING_DEPS[@]}"
        echo "✓ Dependencies installed"
    fi
else
    echo "✓ All dependencies are installed"
fi

# Completion
echo ""
echo "========================================="
echo "Setup Complete!"
echo "========================================="
echo ""
echo "Configuration file: $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. Reboot the system: sudo reboot"
echo "  2. After reboot, Chromium should auto-start with Unifi Protect"
echo "  3. Screen will automatically turn off after 15 minutes of inactivity"
echo ""
echo "Manual controls:"
echo "  - Screen Off: Double-click 'Screen-Off.sh' on desktop"
echo "  - Screen On: Double-click 'Screen-On.sh' on desktop"
echo ""
echo "For troubleshooting, see SETUP.md"
echo ""
read -p "Reboot now? (y/n): " reboot_now

if [[ $reboot_now == "y" || $reboot_now == "Y" ]]; then
    echo "Rebooting..."
    sudo reboot
else
    echo "Remember to reboot before the kiosk will start automatically!"
fi
